DEPRECATION WARNING: Using `bin/rake routes` is deprecated and will be removed in Rails 6.1. Use `bin/rails routes` instead.
 (called from load at /home/namitha/.rvm/gems/ruby-2.6.1/bin/rake:23)
Started GET "/users" for 127.0.0.1 at 2022-04-12 16:46:02 +0530
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (6.0.4.7) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.7) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.7) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.7) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.7) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.7) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.7) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.7.2) lib/rack/proxy.rb:67:in `call'
railties (6.0.4.7) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 16:46:28 +0530
Processing by Api::UsersController#index as HTML
Completed 406 Not Acceptable in 1ms (MongoDB: 0.0ms | Allocations: 979)


  
ActionController::MissingExactTemplate (Api::UsersController#index is missing a template for request formats: text/html):
  
actionpack (6.0.4.7) lib/action_controller/metal/implicit_render.rb:45:in `default_render'
actionpack (6.0.4.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (6.0.4.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (6.0.4.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.4.7) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.4.7) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.4.7) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.4.7) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.4.7) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.4.7) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.4.7) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.4.7) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.4.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.4.7) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.4.7) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.4.7) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
mongoid (7.4.0) lib/mongoid/railties/controller_runtime.rb:21:in `process_action'
actionpack (6.0.4.7) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.4.7) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.4.7) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.4.7) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.4.7) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.4.7) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.4.7) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.4.7) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.4.7) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.4.7) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.4.7) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/cookies.rb:654:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.7) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.7) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.7) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.7) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.7) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.7) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.7) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.7) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.7.2) lib/rack/proxy.rb:67:in `call'
railties (6.0.4.7) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 16:48:33 +0530
Processing by Api::UsersController#index as HTML
Completed 500 Internal Server Error in 115ms (MongoDB: 0.0ms | Allocations: 65824)


  
NameError (undefined local variable or method `user' for #<Api::UsersController:0x00007f139c48b3c0>
Did you mean?  super):
  
app/controllers/api/users_controller.rb:5:in `index'
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 16:48:50 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.7ms | Allocations: 96)
[Webpacker] Compiling...
[Webpacker] Compiled all packs in /home/namitha/Documents/AptanaStudio3Workspace/my_mongo_app/public/packs
[Webpacker] Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.

[Webpacker] Hash: 3cb416f41fa523018972
Version: webpack 4.46.0
Time: 1254ms
Built at: 04/12/2022 4:48:52 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-3cb66649e2322e793167.js   89.2 KiB  application  [emitted] [immutable]  application
js/application-3cb66649e2322e793167.js.map   97.9 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              
Entrypoint application = js/application-3cb66649e2322e793167.js js/application-3cb66649e2322e793167.js.map
[./app/javascript/channels sync recursive _channel\.js$] ./app/javascript/channels sync _channel\.js$ 160 bytes {application} [built]
[./app/javascript/channels/index.js] 211 bytes {application} [built]
[./app/javascript/packs/application.js] 707 bytes {application} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {application} [built]
    + 2 hidden modules

Completed 200 OK in 2340ms (Views: 2335.9ms | MongoDB: 0.0ms | Allocations: 21381)


MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:3 | my_mongo_app_development.insert | STARTED | {"insert"=>"users", "ordered"=>true, "documents"=>[{"_id"=>1, "firstname"=>"albert", "lastname"=>"einstein", "email"=>"ae@relativity.com", "updated_at"=>2022-04-12 11:56:09 UTC, "created_at"=>2022-04-12 11:56:09 UTC}], "$db"=>"my_mongo_app_development...
MONGODB | localhost:27017 req:6 | my_mongo_app_development.insert | SUCCEEDED | 0.026s
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:26:26 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.1ms | Allocations: 8)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 12ms (Views: 6.5ms | MongoDB: 0.0ms | Allocations: 7192)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:26:26 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.1ms | Allocations: 7)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 6ms (Views: 4.9ms | MongoDB: 0.0ms | Allocations: 3364)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:29:06 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.0ms | Allocations: 8)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 3ms (Views: 2.9ms | MongoDB: 0.0ms | Allocations: 3366)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:29:07 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.1ms | Allocations: 7)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 4ms (Views: 3.3ms | MongoDB: 0.0ms | Allocations: 3361)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:32:40 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.5ms | Allocations: 203)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 14ms (Views: 8.4ms | MongoDB: 0.0ms | Allocations: 10720)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:32:41 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.1ms | Allocations: 8)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 5ms (Views: 4.9ms | MongoDB: 0.0ms | Allocations: 3370)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:32:42 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.1ms | Allocations: 8)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 5ms (Views: 4.5ms | MongoDB: 0.0ms | Allocations: 3367)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:32:42 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.1ms | Allocations: 8)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 5ms (Views: 4.5ms | MongoDB: 0.0ms | Allocations: 3371)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:33:46 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:6 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 19.2ms | Allocations: 3917)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 24ms (Views: 23.2ms | MongoDB: 0.0ms | Allocations: 7907)


MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::OperationFailure: [11600:InterruptedAtShutdown]: interrupted at shutdown
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::OperationFailure: [11600:InterruptedAtShutdown]: interrupted at shutdown
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017, sconn:1)
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017, sconn:4)
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | localhost:27017 req:69 conn:2:2 sconn:5 | my_mongo_app_development.insert | STARTED | {"insert"=>"users", "ordered"=>true, "documents"=>[{"_id"=>BSON::ObjectId('6255697802b644439cbda6b8'), "firstname"=>"albert", "lastname"=>"einstein", "email"=>"ae@relativity.com", "updated_at"=>2022-04-12 12:05:53 UTC, "created_at"=>2022-04-12 12:05:5...
MONGODB | localhost:27017 req:69 | my_mongo_app_development.insert | SUCCEEDED | 0.003s
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::OperationFailure: [11600:InterruptedAtShutdown]: interrupted at shutdown
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::OperationFailure: [11600:InterruptedAtShutdown]: interrupted at shutdown
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017, sconn:4)
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: EOFError: end of file reached (for 127.0.0.1:27017 (no TLS)) (on localhost:27017, sconn:3)
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error checking localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'unknown'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Error running awaited hello on localhost:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on localhost:27017)
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:53:06 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | localhost:27017 req:126 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:126 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 3.4ms | Allocations: 2330)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 7ms (Views: 7.0ms | MongoDB: 0.0ms | Allocations: 5595)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:53:07 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:127 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:127 | my_mongo_app_development.find | SUCCEEDED | 0.000s
  Rendered api/users/index.html.erb within layouts/application (Duration: 1.6ms | Allocations: 1580)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 5ms (Views: 4.3ms | MongoDB: 0.0ms | Allocations: 4839)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:53:08 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:128 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:128 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 3.3ms | Allocations: 1575)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 9ms (Views: 8.2ms | MongoDB: 0.0ms | Allocations: 4838)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:53:08 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:129 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:129 | my_mongo_app_development.find | SUCCEEDED | 0.000s
  Rendered api/users/index.html.erb within layouts/application (Duration: 2.2ms | Allocations: 1079)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 8ms (Views: 7.6ms | MongoDB: 0.0ms | Allocations: 4339)


MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone' [awaited].
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:58:39 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:163 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:163 | my_mongo_app_development.find | SUCCEEDED | 0.000s
  Rendered api/users/index.html.erb within layouts/application (Duration: 2.0ms | Allocations: 1580)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 12ms (Views: 6.4ms | MongoDB: 0.0ms | Allocations: 8644)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:58:40 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:164 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:164 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 2.1ms | Allocations: 1594)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 6ms (Views: 5.1ms | MongoDB: 0.0ms | Allocations: 4857)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:58:40 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:165 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:165 | my_mongo_app_development.find | SUCCEEDED | 0.000s
  Rendered api/users/index.html.erb within layouts/application (Duration: 3.5ms | Allocations: 1594)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 10ms (Views: 9.1ms | MongoDB: 0.0ms | Allocations: 4853)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 17:58:41 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:166 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:166 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 2.0ms | Allocations: 1594)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 6ms (Views: 5.3ms | MongoDB: 0.0ms | Allocations: 4856)


MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | localhost:27017 req:230 conn:3:3 sconn:7 | my_mongo_app_development.insert | STARTED | {"insert"=>"users", "ordered"=>true, "documents"=>[{"_id"=>BSON::ObjectId('6255716402b644439cbda6b9'), "firstname"=>"albert", "lastname"=>"einstein", "email"=>"ae@relativity.com", "updated_at"=>2022-04-12 12:32:39 UTC, "created_at"=>2022-04-12 12:32:3...
MONGODB | localhost:27017 req:230 | my_mongo_app_development.insert | SUCCEEDED | 0.001s
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 18:02:47 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:192 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:192 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 2.2ms | Allocations: 1626)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 6ms (Views: 5.7ms | MongoDB: 0.0ms | Allocations: 4886)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 18:04:39 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:204 conn:3:2 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x70170001313820 type=uuid data=0x0a9b1c261bd249ee...>}}
MONGODB | localhost:27017 req:204 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 2.9ms | Allocations: 1605)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 13ms (Views: 8.0ms | MongoDB: 0.0ms | Allocations: 8675)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 20:23:31 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:10 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47457418337780 type=uuid data=0xda4f4bb0c9fc4c11...>}}
MONGODB | localhost:27017 req:6 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 14.7ms | Allocations: 4584)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 38ms (Views: 21.9ms | MongoDB: 0.0ms | Allocations: 14937)


MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for 127.0.0.1 at 2022-04-12 20:29:23 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:42 conn:1:1 sconn:10 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47457418337780 type=uuid data=0xda4f4bb0c9fc4c11...>}}
MONGODB | localhost:27017 req:42 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 1.9ms | Allocations: 1647)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 6ms (Views: 4.9ms | MongoDB: 0.0ms | Allocations: 4926)


Started GET "/api/users" for 127.0.0.1 at 2022-04-12 20:29:24 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:43 conn:1:1 sconn:10 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47457418337780 type=uuid data=0xda4f4bb0c9fc4c11...>}}
MONGODB | localhost:27017 req:43 | my_mongo_app_development.find | SUCCEEDED | 0.000s
  Rendered api/users/index.html.erb within layouts/application (Duration: 1.4ms | Allocations: 1647)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 5ms (Views: 4.4ms | MongoDB: 0.0ms | Allocations: 4919)


MONGODB | localhost:27017 req:959 conn:3:3 sconn:7 | my_mongo_app_development.insert | STARTED | {"insert"=>"users", "ordered"=>true, "documents"=>[{"_id"=>BSON::ObjectId('6255959d02b644439cbda6ba'), "firstname"=>"james", "lastname"=>"bond", "email"=>"007@gmail.com", "updated_at"=>2022-04-12 15:07:20 UTC, "created_at"=>2022-04-12 15:07:20 UTC}], ...
MONGODB | localhost:27017 req:959 | my_mongo_app_development.insert | SUCCEEDED | 0.001s
Started GET "/api/users" for 127.0.0.1 at 2022-04-13 12:29:41 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:3 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47304113621820 type=uuid data=0x5a2060d4a68242d3...>}}
MONGODB | localhost:27017 req:6 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendered api/users/index.html.erb within layouts/application (Duration: 10.9ms | Allocations: 4616)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 34ms (Views: 26.7ms | MongoDB: 0.0ms | Allocations: 14901)


MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for 127.0.0.1 at 2022-04-13 17:02:43 +0530
Processing by Api::UsersController#index as HTML
  Rendering api/users/index.html.erb within layouts/application
MONGODB | localhost:27017 req:1531 conn:1:1 sconn:3 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x69926027134640 type=uuid data=0xdf308d9d325648ef...>}}
MONGODB | localhost:27017 req:1531 | my_mongo_app_development.find | SUCCEEDED | 0.000s
  Rendered api/users/index.html.erb within layouts/application (Duration: 1.4ms | Allocations: 1705)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 5ms (Views: 4.2ms | MongoDB: 0.0ms | Allocations: 4986)


MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:8 | my_mongo_app_development.insert | STARTED | {"insert"=>"articles", "ordered"=>true, "documents"=>[{"_id"=>BSON::ObjectId('6256b77402b6441bf4f2b923'), "name"=>"article", "content"=>"article content", "updated_at"=>2022-04-13 11:43:58 UTC, "created_at"=>2022-04-13 11:43:58 UTC}], "$db"=>"my_mongo...
MONGODB | localhost:27017 req:6 | my_mongo_app_development.insert | SUCCEEDED | 0.048s
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for 127.0.0.1 at 2022-04-13 17:27:54 +0530
Processing by Api::UsersController#index as HTML
MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:11 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47101448480660 type=uuid data=0x45b020f633774d04...>}}
MONGODB | localhost:27017 req:6 | my_mongo_app_development.find | SUCCEEDED | 0.000s
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.7ms | Allocations: 423)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 42ms (Views: 29.3ms | MongoDB: 0.0ms | Allocations: 29850)


MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
MONGODB | localhost:27017 req:104 conn:1:1 sconn:8 | my_mongo_app_development.find | STARTED | {"find"=>"articles", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47108443106920 type=uuid data=0x1bc3a2938b374733...>}}
MONGODB | localhost:27017 req:104 | my_mongo_app_development.find | SUCCEEDED | 0.001s
MONGODB | localhost:27017 req:138 conn:1:1 sconn:8 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"name"=>"james"}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47108443106920 type=uuid data=0x1bc3a2938b374733...>}}
MONGODB | localhost:27017 req:138 | my_mongo_app_development.find | SUCCEEDED | 0.001s
MONGODB | localhost:27017 req:143 conn:1:1 sconn:8 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47108443106920 type=uuid data=0x1bc3a2938b374733...>}}
MONGODB | localhost:27017 req:143 | my_mongo_app_development.find | SUCCEEDED | 0.001s
MONGODB | localhost:27017 req:148 conn:1:1 sconn:8 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>1}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47108443106920 type=uuid data=0x1bc3a2938b374733...>}}
MONGODB | localhost:27017 req:148 | my_mongo_app_development.find | SUCCEEDED | 0.010s
Started GET "/api/users" for 127.0.0.1 at 2022-04-16 13:51:40 +0530
Processing by Api::UsersController#index as HTML
MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:3 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47232500535620 type=uuid data=0x5b2a9694b24f403e...>}}
MONGODB | localhost:27017 req:6 | my_mongo_app_development.find | SUCCEEDED | 0.001s
  Rendering api/users/index.html.erb within layouts/application
  Rendered api/users/index.html.erb within layouts/application (Duration: 0.7ms | Allocations: 440)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 29ms (Views: 16.5ms | MongoDB: 0.0ms | Allocations: 15509)


MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users" for ::1 at 2022-04-16 15:15:14 +0530
Processing by Api::UsersController#index as */*
  Parameters: {"id"=>2, "user"=>{}}
MONGODB | localhost:27017 req:425 conn:1:1 sconn:3 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47232502789080 type=uuid data=0x558dfec7366f4fa0...>}}
MONGODB | localhost:27017 req:425 | my_mongo_app_development.find | SUCCEEDED | 0.001s
Completed 200 OK in 3ms (Views: 0.9ms | MongoDB: 0.0ms | Allocations: 2689)


DEPRECATION WARNING: Using `bin/rake routes` is deprecated and will be removed in Rails 6.1. Use `bin/rails routes` instead.
 (called from load at /home/namitha/.rvm/gems/ruby-2.6.1/bin/rake:23)
Started GET "/api/users/1" for 127.0.0.1 at 2022-04-16 15:16:16 +0530
Processing by Api::UsersController#show as HTML
  Parameters: {"id"=>"1"}
MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>"1"}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47167302495600 type=uuid data=0x7bffdfc8ced24de8...>}}
MONGODB | localhost:27017 req:6 | my_mongo_app_development.find | SUCCEEDED | 0.009s
Completed 404 Not Found in 28ms (MongoDB: 0.0ms | Allocations: 14234)


  
Mongoid::Errors::DocumentNotFound (
message:
  Document(s) not found for class User with id(s) 1.
summary:
  When calling User.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 1 ... (1 total) and the following ids were not found: 1.
resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.):
  
app/controllers/api/users_controller.rb:10:in `show'
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users/1" for 127.0.0.1 at 2022-04-16 15:17:30 +0530
Processing by Api::UsersController#show as HTML
  Parameters: {"id"=>"1"}
Completed 500 Internal Server Error in 11ms (MongoDB: 0.0ms | Allocations: 4341)


  
Mongoid::Errors::InvalidFind (
message:
  Calling Document.find with nil is invalid.
summary:
  Document.find expects the parameters to be 1 or more ids, and will return a single document if 1 id is provided, otherwise an array of documents if multiple ids are provided.
resolution:
  Most likely this is caused by passing parameters directly through to the find, and the parameter either is not present or the key from which it is accessed is incorrect.):
  
app/controllers/api/users_controller.rb:10:in `show'
Started GET "/api/users/1" for 127.0.0.1 at 2022-04-16 15:18:33 +0530
Processing by Api::UsersController#show as HTML
  Parameters: {"id"=>"1"}
MONGODB | localhost:27017 req:20 conn:1:1 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>"1"}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47167302495600 type=uuid data=0x7bffdfc8ced24de8...>}}
MONGODB | localhost:27017 req:20 | my_mongo_app_development.find | SUCCEEDED | 0.001s
Completed 404 Not Found in 8ms (MongoDB: 0.0ms | Allocations: 5135)


  
Mongoid::Errors::DocumentNotFound (
message:
  Document(s) not found for class User with id(s) 1.
summary:
  When calling User.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 1 ... (1 total) and the following ids were not found: 1.
resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.):
  
app/controllers/api/users_controller.rb:10:in `show'
Started GET "/api/users/1" for 127.0.0.1 at 2022-04-16 15:21:12 +0530
Processing by Api::UsersController#show as HTML
  Parameters: {"id"=>"1"}
MONGODB | localhost:27017 req:37 conn:1:1 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>"1"}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47167302495600 type=uuid data=0x7bffdfc8ced24de8...>}}
MONGODB | localhost:27017 req:37 | my_mongo_app_development.find | SUCCEEDED | 0.000s
Completed 404 Not Found in 12ms (MongoDB: 0.0ms | Allocations: 5538)


  
Mongoid::Errors::DocumentNotFound (
message:
  Document(s) not found for class User with id(s) 1.
summary:
  When calling User.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 1 ... (1 total) and the following ids were not found: 1.
resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.):
  
app/controllers/api/users_controller.rb:11:in `show'
Started GET "/api/users/1" for 127.0.0.1 at 2022-04-16 15:21:45 +0530
Processing by Api::UsersController#show as HTML
  Parameters: {"id"=>"1"}
MONGODB | localhost:27017 req:41 conn:1:1 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>1}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47167302495600 type=uuid data=0x7bffdfc8ced24de8...>}}
MONGODB | localhost:27017 req:41 | my_mongo_app_development.find | SUCCEEDED | 0.000s
Completed 200 OK in 5ms (Views: 0.2ms | MongoDB: 0.0ms | Allocations: 5196)


MONGODB | Topology type 'unknown' initializing.
MONGODB | There was a change in the members of the 'Unknown' topology.
MONGODB | Server localhost:27017 initializing.
MONGODB | Waiting for up to 30.00 seconds for servers to be scanned: #<Cluster topology=Unknown[localhost:27017] servers=[#<Server address=localhost:27017 UNKNOWN>]>
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | Topology type 'Unknown' changed to type 'Single'.
MONGODB | localhost:27017 req:6 conn:1:1 sconn:9 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>1}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47253203317800 type=uuid data=0x3a968a0f61a64d8f...>}}
MONGODB | localhost:27017 req:6 | my_mongo_app_development.find | SUCCEEDED | 0.000s
MONGODB | localhost:27017 req:7 conn:1:1 sconn:9 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>"1"}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47253203317800 type=uuid data=0x3a968a0f61a64d8f...>}}
MONGODB | localhost:27017 req:7 | my_mongo_app_development.find | SUCCEEDED | 0.001s
MONGODB | Server description for localhost:27017 changed from 'standalone' to 'standalone'.
MONGODB | There was a change in the members of the 'Single' topology.
Started GET "/api/users/1" for 127.0.0.1 at 2022-04-16 15:22:43 +0530
Processing by Api::UsersController#show as HTML
  Parameters: {"id"=>"1"}
MONGODB | localhost:27017 req:48 conn:1:1 sconn:6 | my_mongo_app_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>1}, "$db"=>"my_mongo_app_development", "lsid"=>{"id"=><BSON::Binary:0x47167302495600 type=uuid data=0x7bffdfc8ced24de8...>}}
MONGODB | localhost:27017 req:48 | my_mongo_app_development.find | SUCCEEDED | 0.000s
Completed 200 OK in 6ms (Views: 0.5ms | MongoDB: 0.0ms | Allocations: 5342)


